spark:
  app_name: "FIAP PySpark"

paths:
  pedidos: "data/datasets-csv-pedidos/data/pedidos"
  pagamentos: "data/dataset-json-pagamentos/data/pagamentos"
  output: "output/relatorio"

file_options:
  pedidos_csv:
    header: true
    sep: ";"